apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  containers:
    - name:  frontend
      image: 780395309002.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
      command: [ "sleep" ]
      args: [ "infinity" ]

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080