apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::780395309002:role/ssm-for-eks

---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  serviceAccountName: cart
  containers:
    - name:  frontend
      image: 780395309002.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
      command: [ "sleep" ]
      args: [ "infinity" ]
  initContainers:
    - name: aws-ssm-param-store
      image: 780395309002.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:2.0.1
      args: [ "sample:dev.docdb.pass" ]


---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
