apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::780395309002:role/ssm-for-eks

---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec:
  serviceAccountName: catalogue
  containers:
    - name:  catalogue
      image: 780395309002.dkr.ecr.us-east-1.amazonaws.com/catalogue:2.0.1
      command: [ "sleep" ]
      args: [ "infinity" ]
      volumeMounts:
        - mountPath: /params
          name: params
  initContainers:
    - name: aws-ssm-param-store
      image: 780395309002.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:2.0.2
      args: [ "DOCUMENTDB:prod.catalogue.mongo" ]
      volumeMounts:
        - mountPath: /params
          name: params
  volumes:
    - name: params
      emptyDir:
        sizeLimit: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080