apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec:
  containers:
    - name:  frontend
      image: 780395309002.dkr.ecr.us-east-1.amazonaws.com/catalogue:2.0.0
      command: [ "sleep" ]
      args: [ "infinity" ]

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080